apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - port: 1080
    targetPort: 8080
