apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - port: 1080
    name: socks
    targetPort: 8080
  - port: 8080
    name: alternatehttp
    targetPort: 8080
