apiVersion: egress-proxy.barpilot.io/v1alpha1
kind: Request
metadata:
  name: request-sample
spec:
  condition:
    destinations:
      - google.com
      - google.fr
    # urls:
    #   matches:
    #     - .*gif$
    #   are:
    #     - /toto
    #   prefixes:
    #     - /api
    sourceEndpoints: my-headless-service
  action:
    block: true
    reroute: "https://www.qwant.com"
