name: Publish PR Docker image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    name: build egress-proxy-operator image
    runs-on: ubuntu-latest
    outputs:
      image: ghcr.io/guilhem/egress-proxy-operator@${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: image meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/guilhem/egress-proxy-operator

      - name: build push
        uses: docker/build-push-action@v2
        id: build
        with:
          context: ./wp-base/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha
            type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=gha,mode=max
